# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [45]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [48]:
A = np.arange(1, 16).reshape(3,5)

In [50]:
# Print information about the matrix A
print("Dimension (number of axes):", A.ndim)       # Prints the number of dimensions (axes) of the matrix
print("Shape (form):", A.shape)                   # Prints the shape of the matrix as (rows, columns)
print("Size (number of elements):", A.size)       # Prints the total number of elements in the matrix
print("Datatype (data type):", A.dtype)           # Prints the data type of the elements in the matrix


Dimension (number of axes): 2
Shape (form): (3, 5)
Size (number of elements): 15
Datatype (data type): int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [53]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [55]:
# Elementwise subtraction
subtraction = B - C
print("\nElementwise subtraction:")
print(subtraction)

# Elementwise multiplication
elementwise_multiplication = B * C
print("\nElementwise multiplication:")
print(elementwise_multiplication)

# Matrix multiplication
matrix_multiplication = B @ C
print("\nMatrix multiplication:")
print(matrix_multiplication)


Elementwise subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [58]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
# Exponentiate each number elementwise
exp_matrix = np.exp(B)
print("\nExponentiate each element (np.exp):")
print(exp_matrix)

# Calculate the minimum value in the whole matrix
min_value = np.min(B)
print("\nMinimum value in the whole matrix:")
print(min_value)

# Calculate the minimum value in each row
min_in_rows = np.min(B, axis=1)
print("\nMinimum value in each row:")
print(min_in_rows)

# Calculate the minimum value in each column
min_in_columns = np.min(B, axis=0)
print("\nMinimum value in each column:")
print(min_in_columns)

# Find the index value for the minimum value in the whole matrix
min_index = np.argmin(B)
print("\nIndex of the minimum value in the whole matrix:")
print(min_index)

# Find the index value for the minimum value in each row
min_index_rows = np.argmin(B, axis=1)
print("\nIndex of the minimum value in each row:")
print(min_index_rows)

# Calculate the sum for all elements
sum_elements = np.sum(B)
print("\nSum of all elements:")
print(sum_elements)

# Calculate the mean for each column
mean_columns = np.mean(B, axis=0)
print("\nMean for each column:")
print(mean_columns)

# Calculate the median for each column
median_columns = np.median(B, axis=0)
print("\nMedian for each column:")
print(median_columns)


Exponentiate each element (np.exp):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix:
1

Minimum value in each row:
[1 4 7]

Minimum value in each column:
[1 2 3]

Index of the minimum value in the whole matrix:
0

Index of the minimum value in each row:
[0 0 0]

Sum of all elements:
45

Mean for each column:
[4. 5. 6.]

Median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [63]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [65]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [70]:
# When you provide fewer indices than axes while slicing, NumPy assumes the missing indices correspond to selecting all elements along the remaining axes.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [73]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [77]:
# Iterating elementwise
for i in A.flat:
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [ ]:
#Axis0 (outermost): Represents the number of blocks in the array.
#Axis1 (middle): Represents the rows within each block.
#Axis2 (innermost): Represents the elements (or columns) within each row.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [79]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    """
    Performs addition or multiplication on two matrices according to the rules of vector- and matrix algebra.
    
    Args:
        matrix1 (numpy.ndarray): The first matrix.
        matrix2 (numpy.ndarray): The second matrix.
        operation (str): The operation to perform ('add' or 'multiply').
    
    Returns:
        numpy.ndarray: The resulting matrix after addition or multiplication.
    
    Raises:
        ValueError: If inputs are not numpy arrays, operation is invalid, or matrix dimensions do not conform.
    """
    # Validate input types
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray")
    
    # Validate operation
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be 'add' or 'multiply'")
    
    if operation == 'add':
        # Validate matrix sizes for addition
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        # Perform matrix addition
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        # Validate matrix dimensions for multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix for multiplication")
        # Perform matrix multiplication
        return np.dot(matrix1, matrix2)

# Example usage:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("Addition:")
print(add_mult_matrices(m1, m2, 'add'))

m3 = np.array([[1, 2, 3], [4, 5, 6]])
m4 = np.array([[7, 8], [9, 10], [11, 12]])
print("Multiplication:")
print(add_mult_matrices(m3, m4, 'multiply'))


Addition:
[[ 6  8]
 [10 12]]
Multiplication:
[[ 58  64]
 [139 154]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

In [81]:
# You can check if v1 and v2 are a view or a copy by using the .base attribute:

# If .base is None, it's a copy.
# If .base points to the original array, it's a view.
# If you change the last element in v2 to 123, the last element in v1 will also be changed because v2 is a view, meaning they share the same data buffer.

Object `copy` not found.
